### ISSUE TITLE
Add support for the Events API

### ISSUE THREAD

**Issue by andrerfcsantos** [andrerfcsantos/go-plausible#1]
Recently Plausible introduced the [Events API](https://plausible.io/docs/events-api) that allows custom events to be sent to Plausible. `go-plausible` should also support this endpoint.

## Notes about this task

- Since this request requires a `domain`, this probably should be implemented as method on [Site](https://github.com/andrerfcsantos/go-plausible/blob/main/plausible/site.go) , which contains the domain in the [id field](https://github.com/andrerfcsantos/go-plausible/blob/main/plausible/site.go#L18)
- This endpoint requires information to be sent in the body of the request. The method [client.acquireRequest](https://github.com/andrerfcsantos/go-plausible/blob/2420971d6c25a79fe321a600263b8f6d58068d6d/plausible/client.go#L84) can be used for this, where `formVals QueryArgs` represents the body data.
- This endpoint also requires some extra headers compared to the other requests, as mentioned on the Plausible docs.

## Tasks

- [ ] Implement the functionality for the new kind of request
- [ ] Write tests for the new functionality
- [ ] Update the documentation

**Comment by till** [comment]
@andrerfcsantos hey 👋🏼 — any thoughts on my PR?

**Comment by andrerfcsantos** [comment]
Hey @till, left some comments on the PR.

**Comment by till** [comment]
@andrerfcsantos I think I addressed everything, I would just add the helper if you are happy with what I got. Thanks for taking the time. :)

**Comment by andrerfcsantos** [comment]
I'll close this for now, as the support for the event API is now added with [0.4.0](https://github.com/andrerfcsantos/go-plausible/releases/tag/v0.4.0).

Further improvements to this should be discussed in new issues/PRs.
